### stack: nginx
version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ~/resources/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/resources/nginx/certs/:/ssl/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro