version: "2"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - $(pwd)/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $(pwd)/nginx/certs/:/ssl/