### stack: artifactory

version: '2'

volumes:
 artifactory_data:

services:
  artiweb:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
    container_name: artifactory
    environment:
     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g
    restart: always
    volumes:
     - artifactory_data:/var/opt/jfrog/artifactory
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
     - 80:8081
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000